apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-test-node-app
  template:
    metadata:
      labels:
        app: k8s-test-node-app
    spec:
      containers:
      - name: k8s-test-node-app
        image: psahni/test-node-app:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
